spring:
  application:
    name: qms
  profiles:
    active: "h2"
  main:
    banner-mode: "off"
server:
  port: 8090
  servlet:
    context-path: /qms-server

---
#h2
spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: always
    #jdbc-url: jdbc:h2:mem:testdb
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    data: classpath:h2/data.sql
    username: sa
    password: 
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:  
        hbm2ddl.auto: update
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false

---
#mysql
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qms?useSSL=false
    jdbc-url: jdbc:mysql://localhost:3306/qms?useSSL=false
    username: root
    password: Welcome1
    type: com.zaxxer.hikari.HikariDataSource
    #data: classpath:mysql/data.sql
    data-username: root 
    data-password: Welcome1 
    initialization-mode: always
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    properties: 
      hibernate: 
        hbm2ddl:  
          auto: update
    show-sql: false

